version: '3'

services:
  ml:
    build: ./services/ml
    ports:
      - 9090:9090
    depends_on:
      - rabbitmq
      - loader
  loader:
    build: ./services/loader
    depends_on:
      - rabbitmq
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management-alpine
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
    restart: always
    volumes:
      - rabbitmq:/var/lib/rabbitmq

volumes:
  rabbitmq:
    driver: local
