version: '3'
services:
  ipfs:
    image: ipfs/go-ipfs:latest
    environment:
      - IPFS_PROFILE=server
      - IPFS_PATH=/ipfsdata
    volumes:
      - ./data/ipfs:/ipfsdata
    expose:
      - 5001
      - 8081
      - 8080
      - 4001
    ports:
      - 4001:4001
      - 127.0.0.1:8080:8080
      - 127.0.0.1:8081:8081
      - 127.0.0.1:5001:5001
    networks:
      - docker_network

  stonent-adapter:
    build: ./
    expose:
      - 5001
      - 8081
      - 8080
      - 4001
    ports:
      - 9090:9090
    networks:
      - docker_network
    depends_on:
      - ipfs

networks:
  docker_network:
    driver: bridge
